apiVersion: v1
kind: Service
metadata:
  name: hello-server-service
  namespace: break-and-fix-ns
spec:
  selector:
    app: hello-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
