apiVersion: v1
kind: Pod
metadata:
  name: httpserver-startup
  labels:
    app: httpserver
spec:
  containers:
  - name: httpserver
    image: blux2/delayfailserver:1.1
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
    startupProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 10
      failureThreshold: 3
      periodSeconds: 10
