apiVersion: v1
kind: Service
metadata:
  name: break-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: hello-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30599
